# Generated by Django 5.1.2 on 2025-10-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='video',
        ),
        migrations.AddField(
            model_name='apartment',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter YouTube video URL', null=True),
        ),
    ]
