# Generated by Django 5.1.2 on 2025-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_apartment_video_apartment_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='video_url',
        ),
        migrations.AddField(
            model_name='apartment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='apartments/videos/'),
        ),
    ]
