# Generated by Django 5.1.2 on 2025-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_apartment_video_url_apartment_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='video',
        ),
        migrations.AddField(
            model_name='apartment',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', null=True),
        ),
    ]
