"""
Django settings for APARTMENT project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'your-secret-key'
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'APARTMENT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'main' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'APARTMENT.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "main" / "static"]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'











# Add these to your settings.py for full functionality:

# Email Configuration (for contact form and booking confirmations)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # or your email provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'noreply@ubwiza-apartment.com'
CONTACT_EMAIL = 'tuyambazesylvain5@gmail.com'

# For development - use console backend
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    
    
    
# admin settings customizations
ADMIN_SITE_HEADER = "UBWIZA APARTMENT Admin"
ADMIN_SITE_TITLE = "UBWIZA APARTMENT Admin"
ADMIN_INDEX_TITLE = "Welcome to UBWIZA APARTMENT Admin"
ADMIN_URL = "admin/"
ADMIN_LOGIN_TEMPLATE = "admin/login.html"
ADMIN_LOGOUT_TEMPLATE = "admin/logout.html"
ADMIN_PASSWORD_CHANGE_TEMPLATE = "admin/password_change.html"
ADMIN_PASSWORD_CHANGE_DONE_TEMPLATE = "admin/password_change_done.html"



JAZZMIN_SETTINGS = {
    # title of the window
    "site_title": "UBWIZA APARTMENT Admin",
    
    # Title on the brand, and login screen (19 chars max)
    "site_header": "UBWIZA APARTMENT",
    "site_brand": "UBWIZA APARTMENT",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to UBWIZA APARTMENT Admin",
    
    # Copyright on the footer
    "copyright": "UBWIZA APARTMENT",
    
    # Theme
    "theme": "darkly",
    
    # ================ IMPORTANT: RESTORE MISSING FEATURES ================
    
    # Show "VIEW SITE" button - THIS IS WHAT YOU'RE MISSING!
    "show_ui_builder": True,
    "show_view_site": True,  # This adds the "View Site" button
    
    # Dark mode toggle
    "theme_toggle": True,  # Allows switching between light/dark themes
    
    # Sidebar configuration
    "navigation_expanded": True,
    "navigation_collapse": True,
    
    # Icons for side menu
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.Room": "fas fa-bed",
        "main.Gallery": "fas fa-images",
        "main.Booking": "fas fa-calendar-check",
        "main.ContactMessage": "fas fa-envelope",
        "main.Apartment": "fas fa-building",
    },
    
    # Custom links to add to the side menu
    "custom_links": {
        "main": [{
            "name": "View Website", 
            "url": "/",  # Your website homepage
            "icon": "fas fa-globe",
            "permissions": ["auth.view_user"]
        }]
    },
    
    # Menu order
    "order_with_respect_to": [
        "main",
        "main.Apartment", 
        "main.Room",
        "main.Gallery",
        "main.Booking", 
        "main.ContactMessage",
        "auth",
    ],
    
    # ================ ADDITIONAL USEFUL SETTINGS ================
    
    # Top menu links
    "topmenu_links": [
        {"name": "View Site", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    ],
    
    # Change main menu icons
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Related modal configuration
    "related_modal_active": True,
    
    # UI Tweaks
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_sidebar": True,
    "show_language_chooser": True,
}

# ================ JAZZMIN UI CONFIGURATION ================
# This enables the UI customizer in the admin

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
 